-- Add raw-material fields required by two-file import:
-- 1) item export (品项导出)
-- 2) markup rules export (加价规则导出)

ALTER TABLE raw_materials
  ADD COLUMN IF NOT EXISTS unit_amount NUMERIC(12,4),
  ADD COLUMN IF NOT EXISTS item_main_image TEXT,
  ADD COLUMN IF NOT EXISTS item_identifier TEXT,
  ADD COLUMN IF NOT EXISTS item_spec TEXT,
  ADD COLUMN IF NOT EXISTS item_brand TEXT,
  ADD COLUMN IF NOT EXISTS item_mnemonic_code TEXT,
  ADD COLUMN IF NOT EXISTS item_stat_subject TEXT,
  ADD COLUMN IF NOT EXISTS item_barcode TEXT,
  ADD COLUMN IF NOT EXISTS item_order_barcode TEXT,
  ADD COLUMN IF NOT EXISTS item_management_type TEXT,
  ADD COLUMN IF NOT EXISTS item_shelf_life_unit TEXT,
  ADD COLUMN IF NOT EXISTS item_shelf_life NUMERIC(12,4),
  ADD COLUMN IF NOT EXISTS item_origin TEXT,
  ADD COLUMN IF NOT EXISTS item_storage_method TEXT,
  ADD COLUMN IF NOT EXISTS item_thaw_duration TEXT,
  ADD COLUMN IF NOT EXISTS item_tax_rate TEXT,
  ADD COLUMN IF NOT EXISTS item_purchase_unit TEXT,
  ADD COLUMN IF NOT EXISTS item_purchase_unit_qty NUMERIC(12,4),
  ADD COLUMN IF NOT EXISTS item_purchase_to_inventory NUMERIC(12,4),
  ADD COLUMN IF NOT EXISTS item_order_unit TEXT,
  ADD COLUMN IF NOT EXISTS item_order_unit_qty NUMERIC(12,4),
  ADD COLUMN IF NOT EXISTS item_order_to_inventory NUMERIC(12,4),
  ADD COLUMN IF NOT EXISTS item_consume_unit TEXT,
  ADD COLUMN IF NOT EXISTS item_consume_unit_qty NUMERIC(12,4),
  ADD COLUMN IF NOT EXISTS item_consume_to_inventory NUMERIC(12,4),
  ADD COLUMN IF NOT EXISTS item_volume_cm3 NUMERIC(12,4),
  ADD COLUMN IF NOT EXISTS item_weight_kg NUMERIC(12,4),
  ADD COLUMN IF NOT EXISTS item_inventory_check_types TEXT,
  ADD COLUMN IF NOT EXISTS item_enabled BOOLEAN,
  ADD COLUMN IF NOT EXISTS item_mall_sort_order NUMERIC(12,4),
  ADD COLUMN IF NOT EXISTS item_material_type TEXT,
  ADD COLUMN IF NOT EXISTS item_is_weighing BOOLEAN,
  ADD COLUMN IF NOT EXISTS item_tax_category TEXT,
  ADD COLUMN IF NOT EXISTS item_tax_rate_extra TEXT,
  ADD COLUMN IF NOT EXISTS item_replenish_strategy TEXT,
  ADD COLUMN IF NOT EXISTS item_attr_name TEXT,
  ADD COLUMN IF NOT EXISTS item_raw_payload JSONB,
  ADD COLUMN IF NOT EXISTS markup_template_id TEXT,
  ADD COLUMN IF NOT EXISTS markup_item_identifier TEXT,
  ADD COLUMN IF NOT EXISTS markup_mode TEXT,
  ADD COLUMN IF NOT EXISTS markup_value NUMERIC(12,4),
  ADD COLUMN IF NOT EXISTS markup_raw_payload JSONB;
