#!/usr/bin/env bash
#===========================================================
# mike-product-calc — Install / Upgrade Script
# 用法：
#   # 自动下载最新 release 并安装
#   curl -fsSL https://raw.githubusercontent.com/ericmr1981/mike-product-calc/main/scripts/install.sh | bash
#
#   # 指定版本安装
#   TAG=v0.1.0 bash <(curl -fsSL https://raw.githubusercontent.com/ericmr1981/mike-product-calc/main/scripts/install.sh)
#
#   # 本地目录升级（已有仓库）
#   ./scripts/install.sh --local
#===========================================================

set -euo pipefail

REPO="ericmr1981/mike-product-calc"
ASSET_NAME="mike-product-calc"
INSTALL_DIR="${APP_INSTALL_DIR:-/opt/mike-product-calc}"
TARGET_TAG="${TAG:-latest}"

# 颜色
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

#--------------------------------------------------
# 写入版本信息文件（安装时自动生成，勿手动删除）
#--------------------------------------------------
write_version_file() {
    local tag="$1"
    local installed_at="$2"
    local checksum="$3"
    cat > "$INSTALL_DIR/VERSION.md" <<EOF
# VERSION — auto-generated by install.sh, do NOT edit manually

| Field    | Value                                  |
|----------|----------------------------------------|
| version  | ${tag}                                 |
| installed_at | ${installed_at}                    |
| checksum | ${checksum}                            |
| repo     | ${REPO}                                |

EOF
    info "VERSION.md written."
}

#--------------------------------------------------
# 获取指定 tag 的 tar.gz 下载 URL
#--------------------------------------------------
get_asset_url() {
    local tag="$1"
    # 如果是 latest，先解析出真实 tag
    if [[ "$tag" == "latest" ]]; then
        tag=$(curl -sSL "https://api.github.com/repos/${REPO}/releases/latest" | grep '"tag_name"' | sed 's/.*"tag_name": "\([^"]*\)".*/\1/')
        [[ -z "$tag" ]] && error "无法解析 latest tag，请检查网络或 Token"
    fi
    local url="https://github.com/${REPO}/releases/download/${tag}/${ASSET_NAME}-${tag}.tar.gz"
    echo "$url"
}

#--------------------------------------------------
# 主流程：下载 + 解压 + 写版本文件
#--------------------------------------------------
install_remote() {
    local tag="$TARGET_TAG"
    local asset_url
    asset_url=$(get_asset_url "$tag")

    info "目标版本: ${tag}"
    info "下载地址: ${asset_url}"

    # 下载到临时文件
    local tmp_tar="/tmp/$(basename "$asset_url")"
    info "下载中..."
    if ! curl -fsSL "$asset_url" -o "$tmp_tar"; then
        error "下载失败，请确认版本 ${tag} 存在: https://github.com/${REPO}/releases"
        exit 1
    fi

    # 校验 checksum
    local checksum
    checksum=$(sha256sum "$tmp_tar" | awk '{print $1}')
    info "SHA256: ${checksum}"

    # 创建目标目录
    mkdir -p "$INSTALL_DIR"
    chmod 755 "$INSTALL_DIR"

    # 解压（--overwrite 覆盖已有文件）
    info "解压到 ${INSTALL_DIR} ..."
    tar -xzf "$tmp_tar" -C "$INSTALL_DIR" --overwrite

    # 写版本文件
    local installed_at
    installed_at=$(date '+%Y-%m-%d %H:%M:%S %Z')
    write_version_file "$tag" "$installed_at" "$checksum"

    # 清理
    rm -f "$tmp_tar"

    info "✅ 安装完成！"
    info "应用目录: ${INSTALL_DIR}"
    info "运行方式: streamlit run ${INSTALL_DIR}/app.py"
    info "版本信息: ${INSTALL_DIR}/VERSION.md"
}

#--------------------------------------------------
# 本地升级（已有 git 仓库，直接 checkout tag）
#--------------------------------------------------
install_local() {
    local script_dir
    script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    local repo_dir
    repo_dir="$(cd "$script_dir/.." && pwd)"

    if [[ ! -d "$repo_dir/.git" ]]; then
        error "本地目录不是 git 仓库，请使用远程安装方式。"
        exit 1
    fi

    local tag="${TARGET_TAG}"
    if [[ "$tag" == "latest" ]]; then
        tag=$(curl -sSL "https://api.github.com/repos/${REPO}/releases/latest" | grep '"tag_name"' | sed 's/.*"tag_name": "\([^"]*\)".*/\1/')
    fi

    info "本地升级到: ${tag}"
    git -C "$repo_dir" fetch --tags
    git -C "$repo_dir" checkout "$tag"

    local installed_at
    installed_at=$(date '+%Y-%m-%d %H:%M:%S %Z')
    local checksum
    checksum=$(find "$repo_dir" -type f -not -path "$repo_dir/.git/*" -not -path "$repo_dir/.venv/*" -not -path "$repo_dir/__pycache__/*" | sort | xargs sha256sum 2>/dev/null | sha256sum | awk '{print $1}')
    write_version_file "$tag" "$installed_at" "$checksum"

    info "✅ 本地升级完成！"
    info "运行: cd ${repo_dir} && streamlit run app.py"
}

#--------------------------------------------------
# 帮助
#--------------------------------------------------
usage() {
    cat <<EOF
mike-product-calc 安装/升级脚本

用法:
  curl -fsSL .../install.sh          | bash         # 安装 latest
  TAG=v0.1.0 bash .../install.sh                   # 指定版本
  ./install.sh --local                            # 本地升级（需 git 仓库）

环境变量:
  TAG              版本号（默认 latest）
  APP_INSTALL_DIR  安装目录（默认 /opt/mike-product-calc）
EOF
}

#--------------------------------------------------
# 入口
#--------------------------------------------------
main() {
    if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
        usage; exit 0
    fi

    if [[ "${1:-}" == "--local" ]]; then
        install_local
    else
        install_remote
    fi
}

main "$@"
